env:
  commonjs: true
  es6: true
  node: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules: {
  "no-const-assign": "error",
  "no-console": 0,
  "global-require": 0,
  "import/no-dynamic-require":0
}
